# .project metadata for Vitess
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

schema_version: "1.0.0"
slug: "vitess"
name: "Vitess"
description: "MySQL-compatible, horizontally scalable, cloud-native database solution."
type: "project"
project_lead: "mattlord"
slack_channels:
  - name: "#vitess"
    primary: true

maturity_log:
  - phase: "graduated"
    date: "2019-11-05T00:00:00Z"
    issue: "https://github.com/cncf/toc/pull/306"

repositories: # Full list: https://github.com/orgs/vitessio/repositories?type=all
  - url: "https://github.com/vitessio/vitess"
    primary: true
    # tags: [core, sig-apps] # Optional
  - url: "https://github.com/vitessio/website"
    primary: true
    # tags: [core, sig-apps] # Optional
  - url: "https://github.com/vitessio/arewefastyet"
    primary: false
    # tags: [core, sig-apps] # Optional
  - url: "https://github.com/vitessio/vitess-releaser"
    primary: false
    # tags: [core, sig-apps] # Optional
  - url: "https://github.com/vitessio/vt"
    primary: false
    # tags: [core, sig-apps] # Optional

website: "https://vitess.io/"

artwork: "https://github.com/cncf/artwork/blob/main/examples/graduated.md#vitess-logos"

adopters:
  path: "https://github.com/vitessio/vitess/blob/main/ADOPTERS.md"

package_managers:
  docker: "vitess"
  sonatype: "io.vitess" # AKA Maven Central

social:
  twitter: "https://twitter.com/vitessio"

security:
  policy:
    path: "https://github.com/vitessio/vitess/blob/main/SECURITY.md"
  contact:
    advisory_url: "https://github.com/vitessio/vitess/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/vitessio/vitess/blob/main/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/vitessio/vitess/blob/main/CODE_OF_CONDUCT.md"

legal:
  license:
    path: "https://github.com/vitessio/vitess/blob/main/LICENSE"
  identity_type:
    has_dco: true
    has_cla: false
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/vitessio/vitess/blob/main/README.md"

landscape:
  category: "App Definition and Development"
  subcategory: "Database"

# CLOMonitor Score: 90/100
# Documentation: 100 | License: 100 | Best Practices: 95 | Security: 73
